services:
  # PHP Service
  web_php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_php
    restart: always
    environment:
      SERVICE_NAME: web_php
    ports:
      - "9000:9000"      
    volumes:
      - ./www_data:/var/www/html
      - ./php/php.ini:/usr/src/etc/php/php.ini     
    depends_on:
      -  web_db      
    app-network:
      driver: bridge

  # Nginx Service
  web_nginx:
    image: nginx
    container_name: web_nginx
    restart: always
    environment:
      TZ: "Europe/Moscow"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - web_php
    links:
      - web_php      
    app-network:
      driver: bridge

  # MySQL Service
  web_db:
    image: mysql:8
    container_name: web_db
    restart: always
    environment:
      SERVICE_NAME: web_db
      MYSQL_DATABASE: web_db
      MYSQL_ROOT_PASSWORD: "MyStr0ngP@ssw0rd"
      TZ: "Europe/Moscow"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql      
    app-network:
      driver: bridge

# Docker Networks
networks:
  app-network:
    driver: bridge
    environment:
      TZ: "Europe/Moscow"
