---
- name: Deploy dockered app_php
  hosts: all
  any_errors_fatal: true
  become: true
---
# tasks
tasks:
- name: Install Docker and Docker Compose
  become: true
  apt:
    name:
      - docker.io
      - docker-compose
    state: present

- name: Start containers using docker-compose
  become: true
  ansible.builtin.shell: docker-compose up -d
  args:
    chdir: /

- name: Generate Nginx configuration file from template
  template:
    src: 
    dest: /etc/nginx/conf.d/nginx_php.conf
  notify:
    - restart nginx

- name: restart nginx
  service:
    name: nginx
    state: restarted
    
- name: Check container status
  become: true
  ansible.builtin.shell: docker-compose ps -a
  args:
    chdir: /
  register: container_status
