---
- name: Deploy dockered app_php to remote_host
  hosts: all
  any_errors_fatal: true
  become: yes
---
# vars

vars:
  file_name: mis-llo-1.0.82.0.jar
  service_name: mis-llo
---
# tasks

tasks:

- name: Copy new version file of service to Hosts
  ansible.builtin.copy:
    src: tmp/
    dest: '/ets/{{ service_name }}'

- name: Rewrite working file with new version file of service
  ansible.builtin.copy:
    src: '/opt/quasar/mis/{{ service_name }}/{{ file_name }}'
    dest: '/opt/quasar/mis/{{ service_name }}/{{ service_name }}.jar'
    remote_src: yes

- name: Restart service
  ansible.builtin.service:
    name: "{{ service_name }}"
      
- name: nginx systemd
  systemd:
    name: nginx
    enabled: yes
    state: started
---
- name: Deploy web application
  hosts: web-servers
  become: yes
  roles:
    - docker
    - webapp
    - nginx
---
- name: Install Docker
  apt:
    name: docker.io
    state: latest
- name: Install Docker Compose
  apt:
    name: docker-compose
    state: latest
Шаг 6: Роль для веб-приложения
roles/webapp/tasks/main.yml:

---
- name: Copy docker-compose.yml file
  copy:
    src: files/docker-compose.yml
    dest: /home/ubuntu/docker-compose.yml
Шаг 7: Роль для Nginx
roles/nginx/tasks/main.yml:

---
- name: Generate Nginx configuration file from template
  template:
    src: templates/nginx.conf.j2
    dest: /path/to/your/nginx/conf.d/default.conf
  notify:
    - restart nginx
roles/nginx/handlers/main.yml:

---
- name: restart nginx
  service:
    name: nginx
    state: restarted
      state: restarted
 
