---
- name: Deploy dockered app_php
  hosts: all
  any_errors_fatal: true
  become: yes
---
# vars
vars:
  remote_host: 
---
# tasks

tasks:

- name: Install Docker
  apt:
    name: docker.io
    state: latest
- name: Install Docker Compose
  apt:
    name: docker-compose
    state: latest
    
- name: Copy new version file of service to Hosts
  ansible.builtin.copy:
    src: tmp/
    dest: '/ets/{{ service_name }}'

- name: Rewrite working file with new version file of service
  ansible.builtin.copy:
    src: '/opt/quasar/mis/{{ service_name }}/{{ file_name }}'
    dest: '/opt/quasar/mis/{{ service_name }}/{{ service_name }}.jar'
    remote_src: yes

- name: Restart service
  ansible.builtin.service:
    name: "{{ service_name }}"
      
- name: nginx systemd
  systemd:
    name: nginx
    enabled: yes
    state: started
---
- name: Copy docker-compose.yml file
  copy:
    src: files/docker-compose.yml
    dest: /home/ubuntu/docker-compose.yml
---
- name: Generate Nginx configuration file from template
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/conf.d/nginx_php.conf
  notify:
    - restart nginx
---
- name: restart nginx
  service:
    name: nginx
    state: restarted
 
